In [2]:
import numpy as np

In [3]:
arr = np.array([[87,56,87],[76,78,67]])
print(arr.shape)

(2, 3)


In [4]:
er = np.array([[[87,87,83],[67,98,47]],[[87,34,49],[67,48,98]]])
print(er.shape)

(2, 2, 3)


In [7]:
we = np.array([7,9,7,8,4,8,8,4],ndmin=5)
print(we)
print(we.shape)

[[[[[7 9 7 8 4 8 8 4]]]]]
(1, 1, 1, 1, 8)


In [10]:
ns = np.array([[[8,6,4,5],[4,6,8,9],[8,4,2,1]]],ndmin=5)
print(ns)
print(ns.shape)

[[[[[8 6 4 5]
    [4 6 8 9]
    [8 4 2 1]]]]]
(1, 1, 1, 3, 4)


In [11]:
ns = np.array([[[8,6,4,5],[4,6,8,9],[8,4,2,1],[1,4,8,9]]],ndmin=5)
print(ns)
print(ns.shape)

[[[[[8 6 4 5]
    [4 6 8 9]
    [8 4 2 1]
    [1 4 8 9]]]]]
(1, 1, 1, 4, 4)
