In [1]:
import numpy as np

- 1-D

In [3]:
arry = np.array([34,32,56,76])
print(arry)

[34 32 56 76]


- 2-D

In [7]:
arry = np.array([[23,74,98,67],[42,73,65,87]])
print(arry)

[[23 74 98 67]
 [42 73 65 87]]
