In [1]:
import numpy as np

- 1-D

In [3]:
arry = np.array([34,32,56,76])
print(arry)

[34 32 56 76]


- 2-D

In [7]:
arry = np.array([[23,74,98,67],[42,73,65,87]])
print(arry)

[[23 74 98 67]
 [42 73 65 87]]


In [2]:
import numpy as np

In [4]:
a = np.array([1,3,5,7])
b = np.array([[12,13,14],[15,16,17]])
c = np.array([[[53,86,47],[65,65,34]],[[65,34,27],[53,65,98]]])
d = np.array(74)
print(a)
print(b)
print(c)
print(d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 3 5 7]
[[12 13 14]
 [15 16 17]]
[[[53 86 47]
  [65 65 34]]

 [[65 34 27]
  [53 65 98]]]
74
1
2
3
0


In [5]:
ap = np.array([12,13,14,15], ndmin = 5)
print(ap)
print('number of dimension =',ap.ndim)

[[[[[12 13 14 15]]]]]
number of dimension = 5
