In [3]:
import numpy as np

In [1]:
l = [2,4,6,8]
print(l)
print(type(l))

[2, 4, 6, 8]
<class 'list'>


In [4]:
ary = np.array([2,4,6,8])
print(ary)
print(type(ary))
print(ary.ndim)

[2 4 6 8]
<class 'numpy.ndarray'>
1


In [5]:
print(np.__version__)

1.21.5


In [8]:
sh = np.array([[12,13,14,15],[24,25,26,27]])
print(sh)
print(sh.ndim)

[[12 13 14 15]
 [24 25 26 27]]
2


In [22]:
ty = np.array ([[867,647,576,75],[657,876,345,675],[567,687,758,353],[576,487,354,587]], ndmin=4)
print(ty)
print(ty.ndim)
print(ty.shape)
print(ty.reshape(8,2))
print(ty.reshape(2,8))
print(ty.dtype)
print(ty.size)
print(ty.itemsize)




[[[[867 647 576  75]
   [657 876 345 675]
   [567 687 758 353]
   [576 487 354 587]]]]
4
(1, 1, 4, 4)
[[867 647]
 [576  75]
 [657 876]
 [345 675]
 [567 687]
 [758 353]
 [576 487]
 [354 587]]
[[867 647 576  75 657 876 345 675]
 [567 687 758 353 576 487 354 587]]
int32
16
4
